from __future__ import annotations

from pathlib import Path
from unittest.mock import patch

import pytest
from httpx import AsyncClient
from sqlalchemy.ext.asyncio import AsyncSession

from app.services import skill_revision_service
from app.skills import service as skill_service
from tests.conftest import TEST_USER_ID

pytestmark = pytest.mark.asyncio


def _skill_content(body: str = "Use when summarizing meeting notes.") -> str:
    return (
        "---\n"
        "name: notes\n"
        'description: "Use when summarizing notes into action items."\n'
        "---\n\n"
        f"{body}\n"
    )


async def test_list_revisions_returns_owned_skill_history(
    client: AsyncClient,
    db: AsyncSession,
    tmp_path: Path,
) -> None:
    with patch.object(skill_service.settings, "data_root", str(tmp_path)):
        skill = await skill_service.create_text_skill(
            db,
            user_id=TEST_USER_ID,
            name="Notes",
            slug="notes",
            description="Use when summarizing notes.",
            content=_skill_content(),
        )
        revision = await skill_revision_service.create_revision_for_skill(
            db,
            skill=skill,
            user_id=TEST_USER_ID,
            operation="create",
            changelog_summary="Initial version",
        )
        await db.commit()

        response = await client.get(f"/api/skills/{skill.id}/revisions")

    assert response.status_code == 200, response.text
    body = response.json()
    assert body[0]["id"] == str(revision.id)
    assert body[0]["operation"] == "create"
    assert body[0]["changelog_summary"] == "Initial version"


async def test_get_revision_returns_detail_metadata(
    client: AsyncClient,
    db: AsyncSession,
    tmp_path: Path,
) -> None:
    compatibility = {"targets": {"openai_codex": {"status": "ok"}}}
    with patch.object(skill_service.settings, "data_root", str(tmp_path)):
        skill = await skill_service.create_text_skill(
            db,
            user_id=TEST_USER_ID,
            name="Notes",
            slug="notes",
            description="Use when summarizing notes.",
            content=_skill_content(),
        )
        revision = await skill_revision_service.create_revision_for_skill(
            db,
            skill=skill,
            user_id=TEST_USER_ID,
            operation="builder_create",
            changelog_summary="Generated by builder",
            compatibility_result=compatibility,
        )
        await db.commit()

        response = await client.get(f"/api/skills/{skill.id}/revisions/{revision.id}")

    assert response.status_code == 200, response.text
    body = response.json()
    assert body["changelog_summary"] == "Generated by builder"
    assert body["compatibility_result"] == compatibility
    # 프론트 diff 카드의 베이스라인 선택이 전적으로 의존하는 필드 — 직렬화 고정.
    assert "parent_revision_id" in body


async def test_rollback_revision_restores_content_and_creates_new_revision(
    client: AsyncClient,
    db: AsyncSession,
    tmp_path: Path,
) -> None:
    with patch.object(skill_service.settings, "data_root", str(tmp_path)):
        skill = await skill_service.create_text_skill(
            db,
            user_id=TEST_USER_ID,
            name="Notes",
            slug="notes",
            description="Use when summarizing notes.",
            content=_skill_content("Original guidance."),
        )
        original = await skill_revision_service.create_revision_for_skill(
            db,
            skill=skill,
            user_id=TEST_USER_ID,
            operation="create",
        )
        await skill_service.update_text_content(
            db,
            skill=skill,
            content=_skill_content("Changed guidance."),
        )
        await skill_revision_service.create_revision_for_skill(
            db,
            skill=skill,
            user_id=TEST_USER_ID,
            operation="manual_content_update",
        )
        await db.commit()

        response = await client.post(f"/api/skills/{skill.id}/revisions/{original.id}/rollback")
        content = await skill_service.read_text_content(skill)

    assert response.status_code == 200, response.text
    body = response.json()
    assert "Original guidance." in content
    assert body["revision"]["operation"] == "rollback"
    assert body["skill"]["id"] == str(skill.id)


async def test_list_revisions_for_unowned_skill_returns_404(
    client: AsyncClient,
) -> None:
    response = await client.get("/api/skills/00000000-0000-0000-0000-000000000099/revisions")

    assert response.status_code == 404
