"""make_tool_user_id_nullable_add_is_system

Revision ID: a83f230d7e69
Revises: aa5b4cc59ddb
Create Date: 2026-04-02 10:15:46.445146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a83f230d7e69'
down_revision: Union[str, Sequence[str], None] = 'aa5b4cc59ddb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools', sa.Column('is_system', sa.Boolean(), nullable=False))
    op.alter_column('tools', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tools', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('tools', 'is_system')
    # ### end Alembic commands ###
