const fs = require('fs');
const path = require('path');
const pptxgen = require('pptxgenjs');

function parseArgs(argv) {
  const parsed = {};
  for (let index = 2; index < argv.length; index += 1) {
    const arg = argv[index];
    if (arg === '--input' || arg === '--output') {
      const value = argv[index + 1];
      if (!value) throw new Error(`${arg} requires a value`);
      parsed[arg.slice(2)] = value;
      index += 1;
    }
  }
  if (!parsed.input) throw new Error('--input is required');
  if (!parsed.output) throw new Error('--output is required');
  return parsed;
}

function isInside(root, candidate) {
  const normalizedRoot = path.resolve(root);
  const normalizedCandidate = path.resolve(candidate);
  return normalizedCandidate === normalizedRoot || normalizedCandidate.startsWith(`${normalizedRoot}${path.sep}`);
}

function resolveInput(candidate) {
  const skillDir = process.cwd();
  const outputDir = path.resolve(process.env.OUTPUTS_DIR || process.env.SKILL_OUTPUT_DIR || '.');
  const resolved = path.resolve(skillDir, candidate);
  if (!isInside(skillDir, resolved) && !isInside(outputDir, resolved)) {
    throw new Error(`input must stay inside ${skillDir} or ${outputDir}`);
  }
  return resolved;
}

function resolveOutput(candidate) {
  const outputDir = path.resolve(process.env.OUTPUTS_DIR || process.env.SKILL_OUTPUT_DIR || '.');
  const resolved = path.isAbsolute(candidate)
    ? path.resolve(candidate)
    : path.resolve(outputDir, candidate);
  if (!isInside(outputDir, resolved)) {
    throw new Error(`output must stay inside ${outputDir}`);
  }
  fs.mkdirSync(path.dirname(resolved), { recursive: true });
  return resolved;
}

function addFooter(slide, pageNumber) {
  slide.addText(`Moldy document artifact E2E · ${pageNumber}`, {
    x: 0.55,
    y: 7.05,
    w: 12.2,
    h: 0.25,
    fontFace: 'Arial',
    fontSize: 8,
    color: '667085',
    align: 'right',
  });
}

async function main() {
  const args = parseArgs(process.argv);
  const inputPath = resolveInput(args.input);
  const outputPath = resolveOutput(args.output);
  const spec = JSON.parse(fs.readFileSync(inputPath, 'utf8'));

  const pptx = new pptxgen();
  pptx.layout = 'LAYOUT_WIDE';
  pptx.author = 'Moldy';
  pptx.subject = 'Generated by Moldy PPTX built-in skill';
  pptx.title = String(spec.title || 'Moldy PPTX Presentation');
  pptx.company = 'Moldy';
  pptx.lang = 'ko-KR';
  pptx.theme = {
    headFontFace: 'Arial',
    bodyFontFace: 'Arial',
    lang: 'ko-KR',
  };

  const cover = pptx.addSlide();
  cover.background = { color: 'F6F8FA' };
  cover.addShape(pptx.ShapeType.rect, { x: 0, y: 0, w: 13.333, h: 0.32, fill: { color: '2D6CDF' }, line: { color: '2D6CDF' } });
  cover.addText(String(spec.title || 'Moldy PPTX Presentation'), {
    x: 0.8,
    y: 2.2,
    w: 11.7,
    h: 0.6,
    fontFace: 'Arial',
    fontSize: 34,
    bold: true,
    color: '101828',
  });
  cover.addText(String(spec.subtitle || ''), {
    x: 0.82,
    y: 3.05,
    w: 10.8,
    h: 0.4,
    fontFace: 'Arial',
    fontSize: 17,
    color: '475467',
  });
  addFooter(cover, 1);

  let page = 2;
  for (const item of spec.slides || []) {
    const slide = pptx.addSlide();
    slide.background = { color: 'FFFFFF' };
    slide.addShape(pptx.ShapeType.rect, { x: 0, y: 0, w: 13.333, h: 0.24, fill: { color: '12B76A' }, line: { color: '12B76A' } });
    slide.addText(String(item.title || 'Slide'), {
      x: 0.68,
      y: 0.72,
      w: 11.8,
      h: 0.5,
      fontFace: 'Arial',
      fontSize: 25,
      bold: true,
      color: '101828',
    });
    slide.addText(String(item.body || ''), {
      x: 0.72,
      y: 1.55,
      w: 11.7,
      h: 0.75,
      fontFace: 'Arial',
      fontSize: 15,
      color: '344054',
      breakLine: false,
      fit: 'shrink',
    });
    const bullets = item.bullets || [];
    bullets.forEach((bullet, index) => {
      slide.addText(String(bullet), {
        x: 1.05,
        y: 2.65 + index * 0.62,
        w: 10.8,
        h: 0.4,
        fontFace: 'Arial',
        fontSize: 15,
        color: '101828',
        bullet: { type: 'bullet' },
      });
    });
    addFooter(slide, page);
    page += 1;
  }

  await pptx.writeFile({ fileName: outputPath });
  console.log(JSON.stringify({ ok: true, file: path.basename(outputPath), path: outputPath }));
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
});
