const fs = require('fs');
const path = require('path');
const {
  AlignmentType,
  BorderStyle,
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
} = require('docx');

function parseArgs(argv) {
  const parsed = {};
  for (let index = 2; index < argv.length; index += 1) {
    const arg = argv[index];
    if (arg === '--input' || arg === '--output') {
      const value = argv[index + 1];
      if (!value) throw new Error(`${arg} requires a value`);
      parsed[arg.slice(2)] = value;
      index += 1;
    }
  }
  if (!parsed.input) throw new Error('--input is required');
  if (!parsed.output) throw new Error('--output is required');
  return parsed;
}

function isInside(root, candidate) {
  const normalizedRoot = path.resolve(root);
  const normalizedCandidate = path.resolve(candidate);
  return normalizedCandidate === normalizedRoot || normalizedCandidate.startsWith(`${normalizedRoot}${path.sep}`);
}

function resolveInput(candidate) {
  const skillDir = process.cwd();
  const outputDir = path.resolve(process.env.OUTPUTS_DIR || process.env.SKILL_OUTPUT_DIR || '.');
  const resolved = path.resolve(skillDir, candidate);
  if (!isInside(skillDir, resolved) && !isInside(outputDir, resolved)) {
    throw new Error(`input must stay inside ${skillDir} or ${outputDir}`);
  }
  return resolved;
}

function resolveOutput(candidate) {
  const outputDir = path.resolve(process.env.OUTPUTS_DIR || process.env.SKILL_OUTPUT_DIR || '.');
  const resolved = path.isAbsolute(candidate)
    ? path.resolve(candidate)
    : path.resolve(outputDir, candidate);
  if (!isInside(outputDir, resolved)) {
    throw new Error(`output must stay inside ${outputDir}`);
  }
  fs.mkdirSync(path.dirname(resolved), { recursive: true });
  return resolved;
}

function paragraph(text) {
  return new Paragraph({
    children: [new TextRun({ text: String(text), size: 22 })],
    spacing: { after: 160 },
  });
}

function buildTable(tableSpec) {
  if (!tableSpec || !Array.isArray(tableSpec.headers) || !Array.isArray(tableSpec.rows)) {
    return null;
  }
  const makeCell = (text, header = false) =>
    new TableCell({
      width: { size: 50, type: WidthType.PERCENTAGE },
      borders: {
        top: { style: BorderStyle.SINGLE, size: 1, color: 'B8C2CC' },
        bottom: { style: BorderStyle.SINGLE, size: 1, color: 'B8C2CC' },
        left: { style: BorderStyle.SINGLE, size: 1, color: 'B8C2CC' },
        right: { style: BorderStyle.SINGLE, size: 1, color: 'B8C2CC' },
      },
      children: [
        new Paragraph({
          children: [new TextRun({ text: String(text), bold: header, size: 20 })],
        }),
      ],
    });
  const rows = [
    new TableRow({ children: tableSpec.headers.map((header) => makeCell(header, true)) }),
    ...tableSpec.rows.map((row) => new TableRow({ children: row.map((value) => makeCell(value)) })),
  ];
  return new Table({ width: { size: 100, type: WidthType.PERCENTAGE }, rows });
}

async function main() {
  const args = parseArgs(process.argv);
  const inputPath = resolveInput(args.input);
  const outputPath = resolveOutput(args.output);
  const spec = JSON.parse(fs.readFileSync(inputPath, 'utf8'));

  const children = [
    new Paragraph({
      text: String(spec.title || 'Moldy DOCX Document'),
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.CENTER,
      spacing: { after: 160 },
    }),
    new Paragraph({
      children: [new TextRun({ text: String(spec.subtitle || ''), italics: true, size: 22 })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 360 },
    }),
  ];

  for (const section of spec.sections || []) {
    children.push(
      new Paragraph({
        text: String(section.heading || 'Section'),
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 240, after: 160 },
      }),
    );
    for (const text of section.paragraphs || []) children.push(paragraph(text));
    for (const item of section.bullets || []) {
      children.push(new Paragraph({ text: String(item), bullet: { level: 0 }, spacing: { after: 80 } }));
    }
  }

  const table = buildTable(spec.table);
  if (table) children.push(table);

  const doc = new Document({
    creator: 'Moldy',
    description: 'Generated by Moldy DOCX built-in skill',
    title: String(spec.title || 'Moldy DOCX Document'),
    sections: [{ properties: {}, children }],
  });

  const buffer = await Packer.toBuffer(doc);
  fs.writeFileSync(outputPath, buffer);
  console.log(JSON.stringify({ ok: true, file: path.basename(outputPath), path: outputPath }));
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
});
