const fs = require('fs');
const path = require('path');
const XLSX = require('xlsx');

function parseArgs(argv) {
  const parsed = {};
  for (let index = 2; index < argv.length; index += 1) {
    const arg = argv[index];
    if (arg === '--input' || arg === '--output') {
      const value = argv[index + 1];
      if (!value) throw new Error(`${arg} requires a value`);
      parsed[arg.slice(2)] = value;
      index += 1;
    }
  }
  if (!parsed.input) throw new Error('--input is required');
  if (!parsed.output) throw new Error('--output is required');
  return parsed;
}

function isInside(root, candidate) {
  const normalizedRoot = path.resolve(root);
  const normalizedCandidate = path.resolve(candidate);
  return normalizedCandidate === normalizedRoot || normalizedCandidate.startsWith(`${normalizedRoot}${path.sep}`);
}

function resolveInput(candidate) {
  const skillDir = process.cwd();
  const outputDir = path.resolve(process.env.OUTPUTS_DIR || process.env.SKILL_OUTPUT_DIR || '.');
  const resolved = path.resolve(skillDir, candidate);
  if (!isInside(skillDir, resolved) && !isInside(outputDir, resolved)) {
    throw new Error(`input must stay inside ${skillDir} or ${outputDir}`);
  }
  return resolved;
}

function resolveOutput(candidate) {
  const outputDir = path.resolve(process.env.OUTPUTS_DIR || process.env.SKILL_OUTPUT_DIR || '.');
  const resolved = path.isAbsolute(candidate)
    ? path.resolve(candidate)
    : path.resolve(outputDir, candidate);
  if (!isInside(outputDir, resolved)) {
    throw new Error(`output must stay inside ${outputDir}`);
  }
  fs.mkdirSync(path.dirname(resolved), { recursive: true });
  return resolved;
}

function main() {
  const args = parseArgs(process.argv);
  const inputPath = resolveInput(args.input);
  const outputPath = resolveOutput(args.output);
  const spec = JSON.parse(fs.readFileSync(inputPath, 'utf8'));

  const workbook = XLSX.utils.book_new();
  workbook.Props = {
    Title: String(spec.title || 'Moldy XLSX Workbook'),
    Subject: 'Generated by Moldy XLSX built-in skill',
    Author: 'Moldy',
    CreatedDate: new Date('2026-06-07T00:00:00Z'),
  };

  for (const sheet of spec.sheets || []) {
    const headers = Array.isArray(sheet.headers) ? sheet.headers : [];
    const rows = Array.isArray(sheet.rows) ? sheet.rows : [];
    const data = [headers, ...rows];
    const worksheet = XLSX.utils.aoa_to_sheet(data);
    worksheet['!cols'] = headers.map((header) => ({
      wch: Math.max(12, String(header).length + 4),
    }));
    XLSX.utils.book_append_sheet(workbook, worksheet, String(sheet.name || 'Sheet').slice(0, 31));
  }

  if (!workbook.SheetNames.length) {
    const worksheet = XLSX.utils.aoa_to_sheet([['항목', '값'], ['상태', 'empty workbook']]);
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Sheet1');
  }

  XLSX.writeFile(workbook, outputPath);
  console.log(JSON.stringify({ ok: true, file: path.basename(outputPath), path: outputPath }));
}

try {
  main();
} catch (error) {
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
}
